spring:
  application:
    name: config-client-git
  profiles:
    active: test
  cloud:
    config:
      server:
        git:
          uri:
            https://github.com/gumingchao/microservices.git

server:
  port: 8080

