spring:
  application:
    name: config-client
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri:
            https://github.com/gumingchao/microservices.git

server:
  port: 8081

