spring:
  application:
    name: config-client-git
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gumingchao/microservices.git
    sample:
      msg: from git cloud!
     

server:
  port: 8080
  
